import {createTheme} from "@fluentui/react";

export const BlueTheme = createTheme({
    palette: {
        themePrimary: '#0083e8',
        themeLighterAlt: '#f4fafe',
        themeLighter: '#d3eafb',
        themeLight: '#aed8f8',
        themeTertiary: '#60b3f1',
        themeSecondary: '#1c91eb',
        themeDarkAlt: '#0076d1',
        themeDark: '#0064b0',
        themeDarker: '#004a82',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
        green: '#10893e',
        greenLight: '#00cc6a',
        red: '#E74856',
        redDark: '#E81123',
        blue: '#0063B1',
        blueLight: '#0078D7',
        yellow: '#FFEB3B',
        yellowDark: '#FDD835',
        yellowLight: '#FFEE58'
    },
});