import {createTheme} from "@fluentui/react";

export const RedTheme = createTheme({
    palette: {
        themePrimary: '#ff7375',
        themeLighterAlt: '#fff9f9',
        themeLighter: '#ffe9e9',
        themeLight: '#ffd5d6',
        themeTertiary: '#ffabac',
        themeSecondary: '#ff8486',
        themeDarkAlt: '#e66769',
        themeDark: '#c25759',
        themeDarker: '#8f4042',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
        green: '#10893e',
        greenLight: '#00cc6a',
        red: '#E74856',
        redDark: '#E81123',
        blue: '#0063B1',
        blueLight: '#0078D7',
        yellow: '#FFEB3B',
        yellowDark: '#FDD835',
        yellowLight: '#FFEE58'
    }});